version: "3.8"

services:
  app:
    image: actix-api:runtime
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    ports:
      - 8080:8080
    expose:
      - 8080

  db:
    image: postgres:12
    user: 'root'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    restart: always
    expose:
      - 5432

volumes:
  postgres_data:
